version: '3.8'

services:

  # backend API
  facerecognize-api:
    container_name: backend
    # image: node:14.16.0-alpine3.10
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: npm start
    working_dir: /usr/src/app
    environment: 
      POSTGRES_USER: peko
      POSTGRES_PASSWORD: miko
      POSTGRES_HOST: postgres
      POSTGRES_DB: facerecognize-docker
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      REDIS_URL: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes: 
      - ./:/usr/src/app

  # postgres
  postgres:
    build: ./postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: peko
      POSTGRES_PASSWORD: miko
      POSTGRES_HOST: postgres
      POSTGRES_DB: facerecognize-docker
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8

  #redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6378:6379"