version: '3.6'

services:

  # backend API
  facerecognize-api:
    container_name: backend
    # image: node:14.16.0-alpine3.10
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: npm start
    working_dir: /usr/src/app
    environment: 
      POSTGRES_USER: peko
      POSTGRES_PASSWORD: miko
      POSTGRES_HOST: postgres
      POSTGRES_DB: facerecognize-docker
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    links:
      - postgres
    ports:
      - "3000:3000"
    volumes: 
      - ./:/usr/src/app

  # postgres
  postgres:
    build: ./postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: peko
      POSTGRES_PASSWORD: miko
      POSTGRES_HOST: postgres
      POSTGRES_DB: facerecognize-docker
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8